#!/usr/bin/env python3

import argparse
import logging

import efiboots


logging.basicConfig(level=logging.DEBUG)

parser = argparse.ArgumentParser(description="Manage EFI boot variables with this simple GTK GUI.")
parser.add_argument('--version', action='version', version='1.0')
parser.add_argument('--disk')
parser.add_argument('--part')

parsed_args = parser.parse_args()

efiboots.run(parsed_args.disk, parsed_args.part)
